use_frameworks!

target 'AHFuture_Example' do
  pod 'AHFuture', :path => '../'

  target 'AHFuture_Tests' do
    inherit! :search_paths

#    pod 'Quick', '~> 1.0.0'
#  pod 'Nimble', '~> 5.1.1'
  end
end
